name: Run production changelogs
run-name: Run Production changelogs

on:
  push:
    branches:
      - 'production'
      - 'releases/**'

permissions: write-all
jobs:
  conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-git-pull: "true"
          version-file: "version.json"
          version-path: "version"
          skip-on-empty: "false"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          discussion_category_name: 'Release'
          body: ${{ steps.changelog.outputs.clean_changelog }}